# Generated by Django 4.2.7 on 2023-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('ph_no', models.IntegerField()),
            ],
        ),
    ]
