# Generated by Django 4.2.7 on 2023-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='no_of_copies',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
