# Generated by Django 4.2.7 on 2023-11-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0003_rename_price_book_no_of_books_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_no',
            field=models.CharField(max_length=50),
        ),
    ]
