# Generated by Django 4.2.7 on 2023-11-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0004_alter_book_book_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
