# Generated by Django 4.2.7 on 2023-11-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0005_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.JSONField(default={'agri': 'AGRI', 'ai': 'AI', 'bme': 'BME', 'cse': 'CSE', 'it': 'IT'}),
        ),
    ]
