# Generated by Django 4.2.7 on 2023-11-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0007_alter_book_category_alter_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='IT', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
